const dataCars = [
  {
    id: "1",
    title: "BMW I5",
    category: "BMW",
    price: "₹55.6L",
    desc: "The BMW i5 may get a starting price of around ₹55.5L. The Model S is an all-electric car, with the power range from 380 hp 60 kWh to 692 hp on P85D version. The i5 comes with the gasoline generator as a back up the electric motors, while the Model S can travel only 208 to 253 miles on a single charge.",
    img: "http://wendypeterson.org/wp-content/uploads/2018/01/BMW-i5-luxury-electric-car-4k-hd-wallpaper.jpg",
  },
  {
    id: "2",
    title: "BMW 4 Series",
    category: "BMW",
    price: "₹76.7L",
    desc: "The BMW i5 may get a starting price of around ₹76.7L. The Model S is an all-electric car, with the power range from 380 hp 60 kWh to 692 hp on P85D version. The i5 comes with the gasoline generator as a back up the electric motors, while the Model S can travel only 208 to 253 miles on a single charge.",
    img: "https://tse2.mm.bing.net/th?id=OIP.tIbINsBxeIagh1mBkYqB6AHaE8&pid=Api&P=0",
  },
  {
    id: "3",
    title: "BMW M",
    category: "BMW",
    price: "₹46.7L",
    desc: "The BMW i5 may get a starting price of around ₹46.7L. The Model S is an all-electric car, with the power range from 380 hp 60 kWh to 692 hp on P85D version. The i5 comes with the gasoline generator as a back up the electric motors, while the Model S can travel only 208 to 253 miles on a single charge.",
    img: "https://tse4.mm.bing.net/th?id=OIP.TVISLtNS_vImWAUUDZEA8QHaE8&pid=Api&P=0",
  },
  {
    id: "4",
    title: "Jaguar 4A",
    category: "JAGUAR",
    price: "₹73.5L",
    desc: "Jaguar cars price range is Rs 71.60 Lakh to Rs 1.24 Cr. Top 3 Jaguar car model prices are Jaguar F-Pace price (Rs. 77.41 Lakh - 1.51 Cr), Jaguar F-TYPE price (Rs. 98.13 Lakh - 1.53 Cr), Jaguar I-Pace price (Rs. 1.20 - 1.24 Cr). Check out all models February 2023 price below.",
    img: "https://wallpaperaccess.com/full/1604056.jpg",
  },
  {
    id: "5",
    title: "Jaguar 5C",
    category: "JAGUAR",
    price: "₹76.5L",
    desc: "Jaguar cars price range is Rs 71.60 Lakh to Rs 1.24 Cr. Top 3 Jaguar car model prices are Jaguar F-Pace price (Rs. 77.41 Lakh - 1.51 Cr), Jaguar F-TYPE price (Rs. 98.13 Lakh - 1.53 Cr), Jaguar I-Pace price (Rs. 1.20 - 1.24 Cr). Check out all models February 2023 price below.",
    img: "https://tse4.mm.bing.net/th?id=OIP.bfNh2eUQWIxeSrmq16rzdQHaEJ&pid=Api&P=0",
  },
  {
    id: "6",
    title: "Jaguar 8Series",
    category: "JAGUAR",
    price: "₹95.5L",
    desc: "Jaguar cars price range is Rs 71.60 Lakh to Rs 1.24 Cr. Top 3 Jaguar car model prices are Jaguar F-Pace price (Rs. 77.41 Lakh - 1.51 Cr), Jaguar F-TYPE price (Rs. 98.13 Lakh - 1.53 Cr), Jaguar I-Pace price (Rs. 1.20 - 1.24 Cr). Check out all models February 2023 price below.",
    img: "https://tse2.mm.bing.net/th?id=OIP.hyhdzQCVTIXI0eEVUi_ylgHaEK&pid=Api&P=0",
  },
  {
    id: "7",
    title: "AUDI 4L",
    category: "AUDI",
    price: "₹65.5L",
    desc: "Audi cars price range is Rs 43.85 Lakh to Rs 2.22 Cr. Top 3 Audi car model prices are Audi Q5 price (Rs. 61.51 - 67.31 Lakh), Audi Q7 price (Rs. 84.70 - 92.30 Lakh), Audi A4 price (Rs. 43.85 - 51.85 Lakh). Check out all models February 2023 price below.",
    img: "https://tse3.mm.bing.net/th?id=OIP.LNBMEro_6hYkva-XvwTvtAHaEv&pid=Api&P=0",
  },
  {
    id: "8",
    title: "AUDI RS5",
    category: "AUDI",
    price: "₹85.5L",
    desc: "Audi cars price range is Rs 43.85 Lakh to Rs 2.22 Cr. Top 3 Audi car model prices are Audi Q5 price (Rs. 61.51 - 67.31 Lakh), Audi Q7 price (Rs. 84.70 - 92.30 Lakh), Audi A4 price (Rs. 43.85 - 51.85 Lakh). Check out all models February 2023 price below.",
    img: "https://tse2.mm.bing.net/th?id=OIP.JozrzppbbRG-we5bxRT-rwHaFV&pid=Api&P=0",
  },
  {
    id: "9",
    title: "AUDI A6",
    category: "AUDI",
    price: "₹1.20CR",
    desc: "Audi cars price range is Rs 43.85 Lakh to Rs 2.22 Cr. Top 3 Audi car model prices are Audi Q5 price (Rs. 61.51 - 67.31 Lakh), Audi Q7 price (Rs. 84.70 - 92.30 Lakh), Audi A4 price (Rs. 43.85 - 51.85 Lakh). Check out all models February 2023 price below.",
    img: "https://images.hdqwalls.com/wallpapers/audi-a6-55-tfsi-quattro-s-5c.jpg",
  },
];

export default dataCars;
